proxy:
  port: 8080
  container-wait-time: 20000
  authentication: none
  docker:
    internal-networking: true
  specs:
  - id: rap-reg-template
    display-name: Test app for shinyproxy
    container-cmd: ["R", "-e", "shiny::runApp('/root/rapRegTemplate')"]
    container-image: hnskde/rap-reg-template
    container-network: krater-net
logging:
  file:
    shinyproxy.log
