proxy:
  title: mongr
  hide-navbar: true
  landing-page: /
  port: 8080
  container-wait-time: 20000
  authentication: none
  specs:
  - id: rap-reg-template
    display-name: Test app for shinyproxy
    container-cmd: ["R", "-e", "shiny::runApp('/root/rapRegTemplate')"]
    container-image: hnskde/rap-reg-template
    container-network: mongr-net
logging:
  file:
    shinyproxy.log

