version: "3.6"

services:
  shinyproxy:
    image: hnskde/shinyproxy
    container_name: shinyproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - mongr-net
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: shinyproxy
        awslogs-stream: shinyproxy
        awslogs-create-group: "true"

networks:
  mongr-net:
    name: mongr-net
